spring:
  datasource:
    url: "jdbc:mariadb://localhost:3306/mydb"
    driver-class-name: "org.mariadb.jdbc.Driver"
    username: "example"
    password: "example"
  jpa:
    properties:
      hibernate:
        format_sql: "true"

logging:
  level:
    org:
      hibernate:
        SQL: "DEBUG"
        type:
          descriptor:
            sql:
              BasicBinder: "TRACE"
    com:
      stady: "DEBUG"

mybatis:
  type-aliases-package: "com.stady.cosinjpa.model"
  configuration:
    map-underscore-to-camel-case: "true"
  mapper-locations: "mapper/*.xml"

